### PR TITLE
Add Python 3.11 to the testing

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks, but there's already a 311 test

**Comment by cclauss** [comment]
There is?!?  https://github.com/MarcoGorelli/cython-lint/actions/runs/3393345107

**Comment by MarcoGorelli** [comment]
yup https://github.com/MarcoGorelli/cython-lint/actions/runs/3393345105/jobs/5640572484

**Comment by cclauss** [comment]
I see...  Thx.

**Pull request closed without merging**
